# Generated by Django 5.1.6 on 2025-03-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_mentorprofile_status_alter_internship_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
