# Generated by Django 5.1.6 on 2025-04-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_internship_fee_internship_upi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='internship.intern')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='internship.task')),
            ],
        ),
    ]
