# Generated by Django 5.1.6 on 2025-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_mentorprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expertise',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
