# Generated by Django 5.1.6 on 2025-03-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_mentorprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
