# Generated by Django 5.1.6 on 2025-03-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_alter_mentorprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internship.mentor'),
        ),
    ]
