# Generated by Django 5.1.6 on 2025-03-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_remove_internship_mentor_mentorprofile_internship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='expertise',
        ),
    ]
