# Generated by Django 5.1.6 on 2025-04-08 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_alter_internship_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internship.clientprofile'),
        ),
    ]
