# Generated by Django 5.1.6 on 2025-04-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_alter_internship_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='upi_id',
            field=models.CharField(default='khushidhir54@okicici', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerlettertemplate',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internship.clientprofile'),
        ),
    ]
