# Generated by Django 5.1.6 on 2025-03-31 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_remove_mentor_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profiles', to='internship.internship'),
        ),
    ]
