# Generated by Django 5.1.6 on 2025-04-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_alter_internship_upi_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerlettertemplate',
            name='body',
        ),
        migrations.AddField(
            model_name='certificate',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerlettertemplate',
            name='editable_section',
            field=models.TextField(default='This is the editable section of the offer letter.'),
        ),
        migrations.AddField(
            model_name='offerlettertemplate',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='offerlettertemplate',
            name='signature_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
