# Generated by Django 5.1.6 on 2025-04-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_remove_offerlettertemplate_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='project_description',
            field=models.TextField(blank=True, help_text='Description of the project intern will work on.', null=True),
        ),
    ]
