# Generated by Django 5.1.6 on 2025-04-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_internship_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorassignment',
            name='certificate_approval',
            field=models.BooleanField(default=False, help_text='Mentor approval for issuing certificate.'),
        ),
    ]
