# Generated by Django 5.1.6 on 2025-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0013_mentorassignment_certificate_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='github_link',
        ),
        migrations.AddField(
            model_name='intern',
            name='has_paid_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='marked_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='mentor_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internship',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorassignment',
            name='certificate_approval',
            field=models.BooleanField(default=False),
        ),
    ]
