# Generated by Django 5.1.6 on 2025-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0014_remove_task_description_remove_task_github_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorassignment',
            name='certificate_approval',
        ),
        migrations.AddField(
            model_name='intern',
            name='certificate_approval',
            field=models.BooleanField(default=False),
        ),
    ]
