# Generated by Django 5.1.6 on 2025-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_remove_mentorassignment_certificate_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_first_internship',
            field=models.BooleanField(default=False),
        ),
    ]
