# Generated by Django 5.1.6 on 2025-04-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0019_alter_intern_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipschedule',
            name='description',
        ),
        migrations.AddField(
            model_name='internshipschedule',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
