# Generated by Django 5.1.6 on 2025-04-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0020_remove_internshipschedule_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipschedule',
            name='zoom_link',
            field=models.URLField(blank=True, default='http://zoom.com/'),
        ),
    ]
