# Generated by Django 5.1.6 on 2025-03-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_token',
        ),
    ]
